### ISSUE TITLE
Adding aliases for Minetest Game 0.4

### ISSUE THREAD

**Issue by MoNTE48** [FaceDeer/settlements#6]
Unfortunately, my MT 0.4 support fix is not complete. You use many nodes in your schemes that are not present in Minetest_game 0.4. I would like to fix it.
And I will be grateful for a hint on how best to do this according to the style of your code.

I will try to keep the appearance of all buildings unchanged.

**Comment by FaceDeer** [comment]
Some of the corner stairs, perhaps? I seem to recall those weren't present in 0.4.

Anyway, I've done some of this kind of fix in a few schematics in a way that should be easy to adapt. If you crack open medieval_kingsmarket.lua you'll see some modpath checks below the main list of node definitions that are substituting nodes for other nodes based on whether they're registered or not.

For example:

    local n43 = { name = "default:chest", param2 = 1 }

...

     if minetest.get_modpath("commoditymarket_fantasy") and minetest.registered_items["commoditymarket_fantasy:kings_market"] then
    	n43 = { name = "commoditymarket_fantasy:kings_market", param2 = 1 }
    end

This takes a particular chest inside the schematic and turns it into a kingsmarket node if the correct mod is installed and the kings_market node is actually registered. You could do some similar "is this node registered?" checks for the nodes that 0.5 added.
